create or replace PROCEDURE AFFICHE_SERVICE 
(
  SERV IN SERVICE%ROWTYPE 
) AS 
BEGIN
  DBMS_OUTPUT.put_line('NUM SERVICE:: '||SERV.NUM_SERV||'  INT SERVICE:: '||SERV.INT_SERV||' CODE S D :: '||SERV.CODE_S_D||' CHEF SERVICE:: '
  ||SERV.CHEF_SERV);
END AFFICHE_SERVICE;