create or replace FUNCTION CHARGE_PROJET 
(
  ID_PROJ IN PROJET.CODE_PROJET%TYPE
) RETURN NUMBER AS 

CURSOR C_CHARGE IS
  SELECT i.DATE_DEB, i.DATE_FIN 
  FROM INTERVENTION i
  WHERE i.CODE_PROJ=ID_PROJ;
  
SUM_HEURES INTEGER;
BEGIN
  SUM_HEURES := 0;
  for V_CHARGE in C_CHARGE loop
    SUM_HEURES :=SUM_HEURES+((V_CHARGE.DATE_FIN - V_CHARGE.DATE_DEB)*8);
  end loop;  
    
  RETURN SUM_HEURES;
END CHARGE_PROJET;