create or replace FUNCTION INT_SERVICE
(
  ID_SERVICE SERVICE.NUM_SERV%TYPE
) RETURN NUMBER AS 

CURSOR C_INT IS
  SELECT i.DATE_DEB, i.DATE_FIN 
  FROM INTERVENTION i,EMPLOYE e 
  WHERE e.CODE_SER=ID_SERVICE
  AND e.IDENT=i.CODE_EMP;
  
SUM_HEURES INTEGER;
BEGIN
SUM_HEURES := 0;
  for INTERV in C_INT loop
    SUM_HEURES :=SUM_HEURES+((INTERV.DATE_FIN - INTERV.DATE_DEB)*8);
  end loop;  
    
  RETURN SUM_HEURES;
END INT_SERVICE;