/*-------------------------Primary Keys----------------------------------------------------------*/
ALTER TABLE CONTRACT ADD CONSTRAINT CONTRACT_PK PRIMARY KEY ( NUM_CONTRACT );
ALTER TABLE DIRECTION ADD CONSTRAINT DIRECTION_PK PRIMARY KEY ( CODE_DIR );
ALTER TABLE EMPLOYE ADD CONSTRAINT EMPLOYE_PK PRIMARY KEY ( IDENT );
ALTER TABLE INTERVENTION ADD CONSTRAINT INTERVENTION_PK PRIMARY KEY ( CODE_PROJ, CODE_EMP );
ALTER TABLE PROJET ADD CONSTRAINT PROJET_PK PRIMARY KEY ( CODE_PROJET );
ALTER TABLE SERVICE ADD CONSTRAINT SERVICE_PK PRIMARY KEY ( NUM_SERV );
ALTER TABLE SOUS_DIRECTION ADD CONSTRAINT SOUS_DIRECTION_PK PRIMARY KEY ( CODE_S_D );
/*------------------------Foreign Keys--------------------------------------------------------------------------*/
ALTER TABLE CONTRACT ADD CONSTRAINT CONTRACT_FK FOREIGN KEY ( CODE_EMP ) REFERENCES EMPLOYE (IDENT);

ALTER TABLE DIRECTION ADD CONSTRAINT DIRECTION_FK FOREIGN KEY ( DIRECTEUR ) REFERENCES EMPLOYE (IDENT);

ALTER TABLE EMPLOYE ADD CONSTRAINT EMPLOYE_FK FOREIGN KEY ( CODE_SER ) REFERENCES SERVICE ( NUM_SERV );

ALTER TABLE INTERVENTION ADD CONSTRAINT INTERVENTION_FK1 FOREIGN KEY ( CODE_PROJ ) REFERENCES PROJET ( CODE_PROJET );
ALTER TABLE INTERVENTION ADD CONSTRAINT INTERVENTION_FK2 FOREIGN KEY ( CODE_EMP ) REFERENCES EMPLOYE (IDENT);

ALTER TABLE PROJET ADD CONSTRAINT PROJET_FK FOREIGN KEY ( CHEF_PROJET ) REFERENCES EMPLOYE (IDENT);

ALTER TABLE SERVICE ADD CONSTRAINT SERVICE_FK1 FOREIGN KEY ( CODE_S_D ) REFERENCES SOUS_DIRECTION (CODE_S_D);
ALTER TABLE SERVICE ADD CONSTRAINT SERVICE_FK2 FOREIGN KEY ( CHEF_SERV ) REFERENCES EMPLOYE (IDENT);

ALTER TABLE SOUS_DIRECTION ADD CONSTRAINT SOUS_DIRECTION_FK1 FOREIGN KEY ( CODE_D ) REFERENCES DIRECTION ( CODE_DIR );
ALTER TABLE SOUS_DIRECTION ADD CONSTRAINT SOUS_DIRECTION_FK2 FOREIGN KEY ( SOUS_DIRECTEUR ) REFERENCES EMPLOYE (IDENT);

