CREATE TABLE PROJET
(
CODE_PROJET NUMBER(6,0),
NOM_PROJET VARCHAR2(25 BYTE) CONSTRAINT "PROJ_NOM_PROJET_NN" NOT NULL ENABLE,
DATE_DEB DATE CONSTRAINT "PROJ_DATE_DEB_NN" NOT NULL ENABLE,
DATE_FIN_PREV DATE CONSTRAINT "PROJ_DATE_FIN_PREV_NN" NOT NULL ENABLE,
AVANCEMENT NUMBER(6,0) CONSTRAINT "PROJ_AVANCEMENT_ENUM" CHECK( AVANCEMENT IN (0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)),
DATE_FIN_REEL DATE,
CHEF_PROJET NUMBER(6,0)
);