
/*********************AUTO INCREMENTAION DES IDs DES TABLEAUS A L'INSERTION************************/

CREATE SEQUENCE ID_SEQ
  START WITH 1
  INCREMENT BY 1;
  
  CREATE OR REPLACE TRIGGER TRIGGED_IDENT
  BEFORE INSERT ON EMPLOYE
  FOR EACH ROW
  
BEGIN
  :NEW.IDENT := ID_SEQ.NEXTVAL;
END;
/

ALTER TRIGGER TRIGGED_IDENT ENABLE;

/*********************************************/
CREATE SEQUENCE ID_SEQ_CONTRACT
  START WITH 1
  INCREMENT BY 1;
  
 CREATE OR REPLACE TRIGGER TRIGGED_CONTRACT
  BEFORE INSERT ON CONTRACT
  FOR EACH ROW
  
BEGIN
  :NEW.NUM_CONTRACT := ID_SEQ_CONTRACT.NEXTVAL;
END;
/

ALTER TRIGGER TRIGGED_CONTRACT ENABLE;

/**************************************************/

CREATE SEQUENCE ID_SEQ_DIRECTION
  START WITH 1
  INCREMENT BY 1;
  
 CREATE OR REPLACE TRIGGER TRIGGED_DIRECTION
  BEFORE INSERT ON DIRECTION
  FOR EACH ROW
  
BEGIN
  :NEW.CODE_DIR := ID_SEQ_DIRECTION.NEXTVAL;
END;
/

ALTER TRIGGER TRIGGED_DIRECTION ENABLE;

/*******************************************************/
CREATE SEQUENCE ID_SEQ_PROJET
  START WITH 1
  INCREMENT BY 1;
  
 CREATE OR REPLACE TRIGGER TRIGGED_PROJET
  BEFORE INSERT ON PROJET
  FOR EACH ROW
  
BEGIN
  :NEW.CODE_PROJET := ID_SEQ_PROJET.NEXTVAL;
END;
/

ALTER TRIGGER TRIGGED_PROJET ENABLE;

/*************************************************************/

CREATE SEQUENCE ID_SEQ_SERVICE
  START WITH 1
  INCREMENT BY 1;
  
 CREATE OR REPLACE TRIGGER TRIGGED_SERVICE
  BEFORE INSERT ON SERVICE
  FOR EACH ROW
  
BEGIN
  :NEW.NUM_SERV := ID_SEQ_SERVICE.NEXTVAL;
END;
/

ALTER TRIGGER TRIGGED_SERVICE ENABLE;

/***********************************************************************/

CREATE SEQUENCE ID_SEQ_S_D
  START WITH 1
  INCREMENT BY 1;
  
 CREATE OR REPLACE TRIGGER TRIGGED_S_D
  BEFORE INSERT ON SOUS_DIRECTION
  FOR EACH ROW
  
BEGIN
  :NEW.CODE_S_D := ID_SEQ_S_D.NEXTVAL;
END;
/

ALTER TRIGGER TRIGGED_S_D ENABLE;

