
/************************LES VERIFICATION DES DATE A L'INSERTION OU A LA MISE A JOUR*************************************************/

 CREATE OR REPLACE TRIGGER TRIGGED_INT_DATE
  BEFORE INSERT OR UPDATE ON INTERVENTION
  FOR EACH ROW
  
DECLARE
  E_INVALID_DATE EXCEPTION; 
BEGIN
  IF (:NEW.DATE_DEB - :NEW.DATE_FIN >=0) THEN
        RAISE E_INVALID_DATE;
  END IF;
      
  EXCEPTION 
  WHEN E_INVALID_DATE THEN
  DBMS_OUTPUT.PUT_LINE('ERROR DATE :: DATE DEBUT > DATE FIN');
END;
/

ALTER TRIGGER TRIGGED_INT_DATE ENABLE;


/****************************************************************/
CREATE OR REPLACE TRIGGER TRIGGED_PROJET_DATE
  BEFORE INSERT OR UPDATE ON PROJET
  FOR EACH ROW

DECLARE
  E_INVALID_DATE EXCEPTION; 
BEGIN
  IF ((:NEW.DATE_DEB - :NEW.DATE_FIN_PREV >=0)OR(:NEW.DATE_DEB - :NEW.DATE_FIN_REEL >=0)) THEN
        RAISE E_INVALID_DATE;
  END IF;
      
  EXCEPTION 
  WHEN E_INVALID_DATE THEN
  DBMS_OUTPUT.PUT_LINE('ERROR DATE :: DATE DEBUT > DATE FIN');
END;
/

ALTER TRIGGER TRIGGED_PROJET_DATE ENABLE;

/***************************************************************************/

CREATE OR REPLACE TRIGGER TRIGGED_CONTRACT_DATE
  BEFORE INSERT OR UPDATE ON CONTRACT
  FOR EACH ROW
 
DECLARE
  E_INVALID_DATE EXCEPTION; 
BEGIN
  IF (:NEW.DATE_DEB - :NEW.DATE_FIN >=0) THEN
        RAISE E_INVALID_DATE;
  END IF;
      
  EXCEPTION 
  WHEN E_INVALID_DATE THEN
  DBMS_OUTPUT.PUT_LINE('ERROR DATE :: DATE DEBUT > DATE FIN');
END;
/

ALTER TRIGGER TRIGGED_CONTRACT_DATE ENABLE;